# Generated by Django 3.2.25 on 2025-05-16 08:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RTP_Simulator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.IntegerField(unique=True)),
                ('session_key', models.CharField(blank=True, max_length=100, null=True)),
                ('last_active', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
